# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1febc8b3bb366de91fa967cc9b5b74c8cb31d5d8b955d5088ad2295423dc1de7cb3164216428e184233a31244f57e128dbbd4ea826c86461604c2f77ffefcd2d

test:
  secret_key_base: 3a291ba9b180af0178335a9aa58faaf222df1a48833a7c98fe9b367290160a425c93299f816d54e5bfeca71fa65380f9999d39f995f692ebe8378a98aabd6471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
